### ISSUE TITLE
Poll only when screen unlocked

### ISSUE THREAD

**Issue by kuleszdl** [SyntaxBlitz/PluckLock#21] opened 2015-01-21 17:51 UTC
I installed PluckLock to a "obsolete" device to observe CPU usage and I got the impression that PluckLock draws power (by pulling the sensors?) even if the device is not used, that is screen is locked and off.

Is it feasible to check the state of the screen lock and poll sensors only in case the screen is unlocked?

**Comment by SyntaxBlitz** [comment] 2015-01-21 23:57
This is a duplicate of issue #3; I haven't figured out a way to fix this. There *is* a method in the API that lets me disable the SensorManager, but... it doesn't actually work. I might be doing it wrong, but it feels pretty silly.

You can see what I've tried at [this StackOverflow question.](http://stackoverflow.com/questions/26946391/androids-sensormanager-fails-to-effectively-unregister-listeners)

**Closed by SyntaxBlitz** 2015-01-21 23:57 UTC

**Comment by kuleszdl** [comment] 2015-01-22 00:18
Sorry for having overlooked this. I will continue the discussion in #3 then.
